#!/usr/bin/env python3
import os
import subprocess
import sys
import io
import zipfile
import requests

assert len(sys.argv) < 3

original_dir = os.getcwd()
os.chdir(os.path.dirname(os.path.realpath(__file__)))
os.chdir('..')
toplevel_dir = os.getcwd()

cmd = "find electrumsv -type f -name '*.py' -o -name '*.kv'"

files = subprocess.check_output(cmd, shell=True)

with open("app.fil", "wb") as f:
    f.write(files)

print("Found {} files to translate".format(len(files.splitlines())))

# Generate fresh translation template
data_in_path = os.path.join('data_in', 'locale')
if not os.path.exists(data_in_path):
    os.makedirs(data_in_path)
data_out_path = os.path.join('electrumsv', 'data', 'locale')
if not os.path.exists(data_out_path):
    os.makedirs(data_out_path)
cmd = 'xgettext -s --from-code UTF-8 --language Python --no-wrap -f app.fil --output='+ os.path.join(data_in_path, 'messages.pot')
print('Generate template')
os.system(cmd)

crowdin_identifier = 'electrumsv'
crowdin_file_name = 'files[electrumsv-client/messages.pot]'
locale_file_name = os.path.join(data_in_path, 'messages.pot')
crowdin_api_key = None

filename = os.path.expanduser('~/.crowdin_api_key')
if os.path.exists(filename):
    with open(filename) as f:
        crowdin_api_key = f.read().strip()

if "crowdin_api_key" in os.environ:
    crowdin_api_key = os.environ["crowdin_api_key"]

if crowdin_api_key:
    # Push to Crowdin
    print('Push to Crowdin')
    url = ('https://api.crowdin.com/api/project/' + crowdin_identifier + '/update-file?key=' + crowdin_api_key)
    with open(locale_file_name, 'rb') as f:
        files = {crowdin_file_name: f}
        response = requests.request('POST', url, files=files)
    print("", "update-file:", "-"*20, response.text, "-"*20, sep="\n")
    # Build translations
    print('Build translations')
    response = requests.request('GET', 'https://api.crowdin.com/api/project/' + crowdin_identifier + '/export?key=' + crowdin_api_key)
    print("", "export:", "-" * 20, response.text, "-" * 20, sep="\n")

if len(sys.argv) < 2:
    # Download & unzip
    s = requests.request('GET', 'https://crowdin.com/backend/download/project/' + crowdin_identifier + '.zip').content
    zfobj = zipfile.ZipFile(io.BytesIO(s))
else:
    zfobj = zipfile.ZipFile(os.path.join(os.path.relpath(original_dir, os.getcwd()), sys.argv[1]))

print('Unzip translations')
os.chdir('data_in')

for name in zfobj.namelist():
    if name.endswith('/'):
        if not os.path.exists(name):
            os.mkdir(name)
    else:
        with open(name, 'wb') as output:
            output.write(zfobj.read(name))

os.chdir(toplevel_dir)

# Convert .po to .mo
print('Installing')
for lang in os.listdir(data_in_path):
    if lang.startswith('messages'):
        continue
    # Check LC_MESSAGES folder
    msg_in_dir = os.path.join(data_in_path, lang, 'LC_MESSAGES')
    msg_out_dir = os.path.join(data_out_path, lang, 'LC_MESSAGES')
    if not os.path.exists(msg_out_dir):
        os.makedirs(msg_out_dir)
    cmd = 'msgfmt --output-file="{0}/electrumsv.mo" "{1}/electrumsv.po"'.format(msg_out_dir, msg_in_dir)
    print('Installing', lang)
    os.system(cmd)

