#!/bin/bash
#
# This script creates a virtualenv named 'env' and installs all
# python dependencies before activating the env and running Electrum SV.
# If 'env' already exists, it is activated and Electrum SV is started
# without any installations. Additionally, the PYTHONPATH environment
# variable is set properly before running Electrum SV.
#
# python-qt and its dependencies will still need to be installed with
# your package manager.

if [ -e ./env/bin/activate ]; then
    source ./env/bin/activate
else
    virtualenv env -p `which python3`
    source ./env/bin/activate
    python3 setup.py install
fi

export PYTHONPATH="/usr/local/lib/python3.5/site-packages:$PYTHONPATH"

if [ ! -e ./gui/qt/icons_rc.py ]; then
    pyrcc5 icons.qrc -o electrumsv/gui/qt/icons_rc.py
fi

./electrum-sv "$@"

deactivate
