"""Environment variable names"""""

AIORPCX_SOFT_LIMIT = 'AIORPCX_SOFT_LIMIT'
AIORPCX_COST_SOFT_LIMIT = 'AIORPCX_COST_SOFT_LIMIT'
AIORPCX_COST_SLEEP = 'AIORPCX_COST_SLEEP'
AIORPCX_INITIAL_CONCURRENT = 'AIORPCX_INITIAL_CONCURRENT'
AIORPCX_TARGET_RESPONSE_TIME = 'AIORPCX_TARGET_RESPONSE_TIME'
AIORPCX_RECALIBRATE_COUNT = 'AIORPCX_RECALIBRATE_COUNT'
AIORPCX_OUTGOING_CONCURRENT = 'AIORPCX_OUTGOING_CONCURRENT'

GAP_LIMIT_RECEIVING = 'GAP_LIMIT_RECEIVING'
GAP_LIMIT_CHANGE = 'GAP_LIMIT_CHANGE'
