parameters:
  - name: 'onlyPullRequests'
    default: false
    type: boolean
  - name: 'pythonVersion'
    default: 3.10
    type: string

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: ${{ parameters.pythonVersion }}
    addToPath: true
    architecture: x64
  condition: |
    and(
      succeeded(),
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(${{ parameters.onlyPullRequests }}, false)
      )
    )
- script: |
    python3 -m pip install -U pylint
    python3 -m pylint --rcfile .pylintrc electrum-sv electrumsv contrib/scripts
    if [ $? -gt 0 ]
    then
      # https://docs.pylint.org/en/1.6.0/run.html#exit-codes
      echo "##vso[task.complete result=Failed;]DONE"
    fi
  condition: |
    and(
      succeeded(),
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(${{ parameters.onlyPullRequests }}, false)
      )
    )
  enabled: true
  continueOnError: false
  failOnStderr: false
  displayName: 'Pylint Static Analysis'
