name: Trigger Build
on:
  push:
    branches:
      - releases/1.3
      - develop
    pull_request:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: electrumsv/electrumsv-build
        event-type: new-commit
        client-payload: '{"branch": "${{ github.ref_name }}"}'
