name: ci

on:
  push:
    branches:
      - 'release/*'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set Branch Env
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payd:${{ env.BRANCH }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
